import {readFile,readdir,access} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
import {createLab} from './lab-harness.mjs';
const root=new URL('../',import.meta.url),files=await readdir(new URL('js/',root));
for(const f of files)execFileSync(process.execPath,['--check',new URL('js/'+f,root).pathname]);
const text=(await Promise.all([readFile(new URL('index.html',root),'utf8'),...files.map(f=>readFile(new URL('js/'+f,root),'utf8'))])).join('\n');
const refs=new Set([...text.matchAll(/["'`]([^"'`\s<>]+\.(?:png|glb))["'`]/g)].map(m=>m[1]));
for(const p of refs)await access(new URL(p,root));
const html=await readFile(new URL('index.html',root),'utf8');const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(x=>x[1]);if(new Set(ids).size!==ids.length)throw new Error('Duplicate HTML IDs');
if(html.includes('wireApplyAuxPins')||html.includes('io-wire-link'))throw new Error('Unrequested hardware UI');
const {result}=await createLab();if(result.failed)throw new Error('Model decode failure');
console.log(`PASS: ${files.length} ES modules parse; ${refs.size} asset references exist; two page DOM; ${result.loaded}/${result.total} GLBs decode.`);
