import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {imageType,inspectImage,inspectUsbLayout,ensureOtaReady,usbWritePlan,postBootVerified,sha256,APP_OFFSET,OTA_SLOT,FLASH_BYTES} from '../js/firmware-image.js';
import {KitApClient} from '../js/kit-ap.js';
const catalog=JSON.parse(fs.readFileSync(new URL('../firmware-catalog.json',import.meta.url)));
const [a1,a2]=catalog.boards;
function app(board){const b=new Uint8Array(65536);b[0]=0xe9;b[1]=5;b[12]=board.imageChipIds[0];b[32]=0x32;b[33]=0x54;b[34]=0xcd;b[35]=0xab;b.set(new TextEncoder().encode(catalog.version),160);return b}
function factory(board){const f=new Uint8Array(FLASH_BYTES);f.fill(255);f.set(app(board),APP_OFFSET);f[0]=0xe9;f[1]=4;f[12]=board.imageChipIds[0];f[13]=0;for(const [i,at] of [APP_OFFSET,0x1f0000].entries()){const p=0x8000+i*32;f[p]=0xaa;f[p+1]=0x50;f[p+2]=0;f[p+3]=0x10+i;new DataView(f.buffer).setUint32(p+4,at,true);new DataView(f.buffer).setUint32(p+8,OTA_SLOT,true)}return f}
for(const b of [a1,a2])test(`mock ${b.id} image, type, chip and partition verification`,()=>{const application=app(b),merged=factory(b);assert.equal(imageType(application),'app');assert.equal(imageType(merged),'factory');assert.equal(inspectImage(application,'app',b,catalog).chipId,b.imageChipIds[0]);assert.equal(inspectImage(merged,'factory',b,catalog).address,0);assert.throws(()=>inspectImage(merged,'app',b,catalog),/exceeds|descriptor/);assert.throws(()=>inspectImage(application,'factory',b,catalog),/truncated|magic/);const wrong=b===a1?a2:a1;assert.throws(()=>inspectImage(application,'app',wrong,catalog),/chip ID/);application[0]=0;assert.throws(()=>inspectImage(application,'app',b,catalog),/magic/);assert.throws(()=>inspectImage(application.slice(0,200),'app',b,catalog),/truncated/)});
test('mock USB offset, flash probe, armed and erase guards',()=>{const image={bytes:app(a2),boardId:a2.id,kind:'app'};assert.throws(()=>usbWritePlan({image,board:a2,chipId:13,flashBytes:FLASH_BYTES}),/bootloader/);assert.throws(()=>usbWritePlan({image,board:a2,chipId:13,flashBytes:FLASH_BYTES,erase:true,appReady:true}),/Factory/);assert.throws(()=>usbWritePlan({image,board:a2,chipId:5,flashBytes:FLASH_BYTES,appReady:true}),/do not match/);assert.throws(()=>usbWritePlan({image,board:a2,chipId:13,flashBytes:0,appReady:true}),/capacity/);assert.throws(()=>usbWritePlan({image,board:a2,chipId:13,flashBytes:FLASH_BYTES,appReady:true,armed:true}),/DISARM/);const plan=usbWritePlan({image,board:a2,chipId:13,flashBytes:FLASH_BYTES,appReady:true});assert.equal(plan.address,APP_OFFSET);assert.equal(plan.eraseAll,false);assert.equal(plan.flashMode,'keep');const merged={bytes:factory(a2),boardId:a2.id,kind:'factory'};assert.equal(usbWritePlan({image:merged,board:a2,chipId:13,flashBytes:FLASH_BYTES,erase:true}).address,0)});
test('mock OTA ownership, identity, armed, migration, space checks',()=>{const image={bytes:app(a2),kind:'app',boardId:a2.id},info={deviceId:'ZFC-001122334455',boardId:a2.id,armed:false,lockMine:true,benchMode:0,trainingActive:false,fcSetupActive:false,partitionLayout:'ZFC_DUAL_1E0000',freeSketchBytes:OTA_SLOT};const input={info,deviceId:info.deviceId,boardId:a2.id,image,owner:true};assert.doesNotThrow(()=>ensureOtaReady(input));for(const [field,value,re] of [['armed',true,/DISARM/],['partitionLayout','LEGACY',/USB Factory/],['freeSketchBytes',4,/free OTA/],['trainingActive',true,/training/],['benchMode',1,/bench/],['deviceId','ZFC-OTHER',/Device ID/],['boardId',a1.id,/board/]])assert.throws(()=>ensureOtaReady({...input,info:{...info,[field]:value}}),re);assert.throws(()=>ensureOtaReady({...input,owner:false}),/Take Control/);assert.throws(()=>ensureOtaReady({...input,image:{...image,kind:'factory'}}),/Application/)});
test('mock ZFC3 chunk sequence, exact offsets, interruption',async()=>{const bytes=new Uint8Array(2300).fill(42),calls=[],c=new KitApClient();c.channel=true;c.owner=true;c.deviceId='ZFC-001122334455';c.request=async(path,data)=>{calls.push({path,data});return path.endsWith('/chunk')?{offset:data.offset+data.data.length/2}:{ok:true}};await c.upload(bytes,'ZFC-A2',await sha256(bytes),()=>{});assert.deepEqual(calls.map(x=>x.path),['/api/firmware/begin','/api/firmware/chunk','/api/firmware/chunk','/api/firmware/chunk','/api/firmware/end']);assert.deepEqual(calls.filter(x=>x.data?.offset!==undefined).map(x=>x.data.offset),[0,1024,2048]);assert(calls.filter(x=>x.data?.data).every(x=>x.data.data.length<=2048));calls.length=0;c.request=async(path,data)=>{calls.push(path);return path.endsWith('/chunk')?{offset:0}:{ok:true}};await assert.rejects(c.upload(bytes,'ZFC-A2',await sha256(bytes)),/offset mismatch/);assert(!calls.includes('/api/firmware/end'));calls.length=0;c.request=async(path,data)=>{calls.push(path);return path.endsWith('/chunk')?{offset:data.offset+data.data.length/2}:{ok:true}};await assert.rejects(c.upload(bytes,'ZFC-A2',await sha256(bytes),()=>{},()=>true),/interrupted/);assert(!calls.includes('/api/firmware/end'))});
test('mock post-boot readback never equates write with boot',()=>{const reported={firmware:catalog.version,boardId:'ZFC-A2'},base={reported,expectedVersion:catalog.version,boardId:'ZFC-A2',deviceId:'ZFC-001122334455',selectedDeviceId:'ZFC-001122334455'};assert(postBootVerified(base));assert(postBootVerified({...base,deviceId:""}));assert(!postBootVerified({...base,reported:null}));assert(!postBootVerified({...base,reported:{...reported,firmware:'18.3.60'}}));assert(!postBootVerified({...base,selectedDeviceId:'ZFC-DIFFERENT'}))});
test('mock SHA mismatch detected against catalog digest',async()=>{const b=app(a2);assert.notEqual(await sha256(b),a2.latest.app.sha256);b[500]^=1;assert.notEqual(await sha256(b),a2.latest.app.sha256)});

test('mock USB readback accepts only matching bootloader and dual OTA partitions',()=>{const f=factory(a2),boot=f.slice(0,4096),table=f.slice(0x8000,0x9000);assert(inspectUsbLayout(boot,table,a2));assert.throws(()=>inspectUsbLayout(boot,table,a1),/bootloader/);table[0]=0;assert.throws(()=>inspectUsbLayout(boot,table,a2),/partition table/)});
